# Generated by Django 2.2 on 2020-08-31 04:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('DojoReads_app', '0003_auto_20200831_0359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='DojoReads_app.Author'),
        ),
    ]
